# Generated by Django 3.2.5 on 2021-07-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('col_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration_acad',
            fields=[
                ('col_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='company/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curr_student',
            fields=[
                ('cstu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('year_joining', models.CharField(max_length=20)),
                ('about', models.TextField(max_length=5000)),
                ('ed_level', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('Research Scholar', 'Research Scholar'), ('Project Staff', 'Project Staff')], default='Research Scholar', max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='student/')),
            ],
        ),
        migrations.CreateModel(
            name='Passed_student',
            fields=[
                ('pstu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('tenure', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=5000)),
                ('ed_level', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('Research Scholar', 'Research Scholar'), ('Project Staff', 'Project Staff')], default='Research Scholar', max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('pos_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('tenure', models.CharField(max_length=50)),
                ('project_value', models.CharField(max_length=50)),
                ('pi', models.CharField(max_length=100)),
                ('copi', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=5000)),
                ('type', models.CharField(choices=[('Consultancy', 'Consultancy'), ('Sponsored', 'Sponsored')], default='Consultancy', max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='project/')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('info', models.TextField(max_length=5000)),
                ('type', models.CharField(choices=[('Patents', 'Patents'), ('Conferences', 'Conferences'), ('Journals', 'Journals'), ('Book_Chapters', 'Book_Chapters')], default='Patents', max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Specialization', 'Specialization'), ('Normal', 'Normal')], default='Normal', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='project/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page.project')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page.company')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('ed_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page.company')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('times_conducted', models.CharField(max_length=20)),
                ('about', models.TextField(max_length=5000)),
                ('special_position', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('clink', models.URLField(default='', max_length=400)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page.company')),
            ],
        ),
    ]
