# Generated by Django 3.2.5 on 2021-07-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(help_text='name of the institution or company', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='company',
            field=models.ForeignKey(default=None, help_text='name of the institution from choices as present in company model', on_delete=django.db.models.deletion.CASCADE, to='page.company'),
        ),
    ]
