# Generated by Django 2.2.17 on 2021-08-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('aw_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField(help_text='Grant or Best Paper Award etc.', max_length=100)),
                ('About', models.TextField(max_length=5000)),
                ('Time', models.CharField(help_text='Type as jan2020 or july2018 and so on', max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('tenure', models.CharField(max_length=1000)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, help_text='Type as author1 | author2 | ... and so on ', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='name',
            field=models.CharField(help_text='industrial agency/company name', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaboration_acad',
            name='name',
            field=models.CharField(help_text='academic agency/institute name', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(help_text='name of the institution or company', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, help_text='Please ignore this field', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='clink',
            field=models.URLField(default='', help_text='Type as full url link e.g. https://github.com/', max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='company',
            field=models.ForeignKey(default=None, help_text='Name of the institution from choices as present in company model', on_delete=django.db.models.deletion.CASCADE, to='page.Company'),
        ),
        migrations.AlterField(
            model_name='course',
            name='special_position',
            field=models.TextField(blank=True, help_text='e.g course coordinator etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='times_conducted',
            field=models.CharField(help_text='Type as tenure1 | tenure2 | ... and so on  for e.g. jan2020 | july2018', max_length=100),
        ),
        migrations.AlterField(
            model_name='curr_student',
            name='about',
            field=models.TextField(help_text='e.g thesis | area of interest | current lab etc', max_length=5000),
        ),
        migrations.AlterField(
            model_name='curr_student',
            name='contact',
            field=models.CharField(help_text='e.g email | phone no | linkedin etc', max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='company',
            field=models.ForeignKey(default=None, help_text='name of the institution from choices as present in company model', on_delete=django.db.models.deletion.CASCADE, to='page.Company'),
        ),
        migrations.AlterField(
            model_name='passed_student',
            name='about',
            field=models.TextField(help_text='e.g current affiliation | new lab etc', max_length=5000),
        ),
        migrations.AlterField(
            model_name='passed_student',
            name='contact',
            field=models.CharField(help_text='e.g email | phone no | linkedin etc', max_length=500),
        ),
        migrations.AlterField(
            model_name='passed_student',
            name='tenure',
            field=models.CharField(help_text='year of passing', max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='if no openings keep single field with name (Positions open: none) else type position names', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='copi',
            field=models.CharField(blank=True, help_text='co-principal investigator', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='featured image', upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(blank=True, help_text='principal investigator', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_value',
            field=models.CharField(blank=True, help_text='in lakhs INR', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='tenure',
            field=models.CharField(help_text='year1-year2 e.g. 2018-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.ImageField(help_text='set of images to be viewed along with project', upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(default=None, help_text='project id connected to set of images', on_delete=django.db.models.deletion.CASCADE, to='page.Project'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(help_text='Type as author1 | author2 | ... and so on ', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='info',
            field=models.TextField(help_text='For journal:journal name and pages(e.g.journal name | page 52-56), book-chapters:name of the book, conferences:name of the conference and location(for e.g. conference name | Delhi), patent:patent id(for e.g PAT/ME/P14050-1/16-17) ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(help_text='For journal:title, book-chapters:title, conferences:topic, patent:title ', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(blank=True, help_text='For journal:issue year(e.g 116(1186):2012), book-chapters:year of publishing, conferences:year of publishing, patent:none ', max_length=20),
        ),
        migrations.AlterField(
            model_name='research',
            name='type',
            field=models.CharField(choices=[('Major Specialization', 'Major Specialization'), ('Normal', 'Normal'), ('Minor Specialization', 'Minor Specialization')], default='Normal', help_text='single specialization and multiple normal research fields', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(help_text='journal name', max_length=100),
        ),
    ]
