# Generated by Django 3.2.5 on 2021-07-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210715_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='name',
            field=models.CharField(help_text='industrial agency/company name', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaboration_acad',
            name='name',
            field=models.CharField(help_text='academic agency/institute name', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, help_text='Please ignore this field', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='clink',
            field=models.URLField(default='', help_text='Type as full url link e.g. https://github.com/', max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='company',
            field=models.ForeignKey(default=None, help_text='Name of the institution from choices as present in company model', on_delete=django.db.models.deletion.CASCADE, to='page.company'),
        ),
        migrations.AlterField(
            model_name='course',
            name='special_position',
            field=models.CharField(help_text='e.g course coordinator etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='times_conducted',
            field=models.CharField(help_text='Type as tenure1 | tenure2 | ... and so on  for e.g. jan2020 | july2018', max_length=100),
        ),
        migrations.AlterField(
            model_name='curr_student',
            name='about',
            field=models.TextField(help_text='e.g thesis | area of interest | current lab etc', max_length=5000),
        ),
        migrations.AlterField(
            model_name='curr_student',
            name='contact',
            field=models.CharField(help_text='e.g email | phone no | linkedin etc', max_length=500),
        ),
        migrations.AlterField(
            model_name='passed_student',
            name='about',
            field=models.TextField(help_text='e.g current affiliation | new lab etc', max_length=5000),
        ),
        migrations.AlterField(
            model_name='passed_student',
            name='contact',
            field=models.CharField(help_text='e.g email | phone no | linkedin etc', max_length=500),
        ),
        migrations.AlterField(
            model_name='passed_student',
            name='tenure',
            field=models.CharField(help_text='year of passing', max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='if no openings keep single field with name (Positions open: none) else type position names', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='copi',
            field=models.CharField(blank=True, help_text='co-principal investigator', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='featured image', upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(blank=True, help_text='principal investigator', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_value',
            field=models.CharField(help_text='in lakhs INR', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='tenure',
            field=models.CharField(help_text='year1-year2 e.g. 2018-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.ImageField(help_text='set of images to be viewed along with project', upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(default=None, help_text='project id connected to set of images', on_delete=django.db.models.deletion.CASCADE, to='page.project'),
        ),
        migrations.AlterField(
            model_name='research',
            name='type',
            field=models.CharField(choices=[('Specialization', 'Specialization'), ('Normal', 'Normal')], default='Normal', help_text='single specialization and multiple normal research fields', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(help_text='journal name', max_length=100),
        ),
    ]
