# Generated by Django 3.2.5 on 2021-07-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210715_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('tenure', models.CharField(max_length=1000)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, help_text='Type as author1 | author2 | ... and so on ', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_value',
            field=models.CharField(blank=True, help_text='in lakhs INR', max_length=50),
        ),
        migrations.AlterField(
            model_name='research',
            name='type',
            field=models.CharField(choices=[('Major Specialization', 'Major Specialization'), ('Normal', 'Normal'), ('Minor Specialization', 'Minor Specialization')], default='Normal', help_text='single specialization and multiple normal research fields', max_length=50),
        ),
    ]
