# Generated by Django 2.2.17 on 2021-07-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20210718_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='special_position',
            field=models.TextField(blank=True, help_text='e.g course coordinator etc', max_length=100),
        ),
    ]
